import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { ENABLE_SMOOTH_CURSOR } from "@/config/ui";

const jetbrainsMonoHeading = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-heading",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, jetbrainsMonoHeading.variable)}
    >
      <body
        className={cn(
          "min-h-full flex flex-col",
          ENABLE_SMOOTH_CURSOR
            ? "smooth-cursor-enabled"
            : "smooth-cursor-disabled"
        )}
      >
        <SmoothCursor enabled={ENABLE_SMOOTH_CURSOR} />
        {children}
      </body>
    </html>
  );
}
